spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatistest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: ndouser
    password: ndopassword
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
    #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: false
